// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8evfxnTsV25SvaeAMr6T0rcoAzHJOjZk',
    appId: '1:337708922037:web:4df990142f59eabc9dfafc',
    messagingSenderId: '337708922037',
    projectId: 'smart-lock-4ee3f',
    authDomain: 'smart-lock-4ee3f.firebaseapp.com',
    storageBucket: 'smart-lock-4ee3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATh89Z72EtUXE1lvfZawMYqeYo4PkLQWk',
    appId: '1:337708922037:android:beaa846cc1d4740e9dfafc',
    messagingSenderId: '337708922037',
    projectId: 'smart-lock-4ee3f',
    storageBucket: 'smart-lock-4ee3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ZrOBi5GeEfLYA1h64XIr6l6ZlWPfs98',
    appId: '1:337708922037:ios:97b73e0ffb2be6f99dfafc',
    messagingSenderId: '337708922037',
    projectId: 'smart-lock-4ee3f',
    storageBucket: 'smart-lock-4ee3f.appspot.com',
    iosClientId: '337708922037-j7f1vhjuq6rparus1ei3slc45bu9n7m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSmartlock',
  );
}
